### ISSUE TITLE
add whatever feature you want - PR welcome

### ISSUE THREAD

**Issue by NisooJadhav** [NisooJadhav/clock#1]
Register for hacktoberfest [here](https://hacktoberfest.com/).

### **Add whatever feature you want, the site lives [here](https://nisoojadhav.github.io/clock/).**
I haven't updated this site for a long time, I want beginners to get their hands on it: fork, edit, commit, and open pull requests.

Suggestions:
(You can add theme changes, icons according to time, responsive CSS changes, etc).

![Completed Wireframe](https://user-images.githubusercontent.com/68807845/194703615-032e84a4-7f51-4bc5-8651-1ef6ae3526f4.png)

Steps:
```
1) Fork this repository.
2) Add features.
3) Commit.
4) Open Pull Request.
```
_I can't wait to see the new features._

**Comment by Samarthasbhat** [comment]
I would like to change the color of the site

**Comment by NisooJadhav** [comment]
> I would like to change the color of the site

Sure!, go ahead. But be minimal :)

**Comment by Agrimaagrawal** [comment]
I would like to  add AM -PM

**Comment by NisooJadhav** [comment]
> I would like to add AM -PM

Sure!, go ahead.

**Comment by shravan2524** [comment]
I want to make responsive.

**Comment by NisooJadhav** [comment]
> I want to make responsive.

the current version is already responsive, will you wait until other people add more features?

**Comment by Agrimaagrawal** [comment]
this project is considered in hacktoberfest?

**Comment by NisooJadhav** [comment]
> this project is considered in hacktoberfest?

after registering, you can make 4 pull requests in any of the open source projects, those requests need to be merged. First 40,000 participants can elect to receive one of two prizes: a tree planted in their name, or the Hacktoberfest 2022 t-shirt.

**Comment by Agrimaagrawal** [comment]
ok

**Comment by BharatChotwani** [comment]
Hello, I can add the `readme.md` file. Kindly assign to me.

**Comment by NisooJadhav** [comment]
> Hello, I can add the `readme.md` file. Kindly assign to me.

Sure!, Go ahead.

**Comment by elixir14082002** [comment]
I would like to add an analog version of the clock. Kindly assign me this issue @NisooJadhav

**Comment by NisooJadhav** [comment]
> I would like to add an analogue version of the clock. Kindly assign me this issue @NisooJadhav 

@elixir14082002 You can start working on it! Please pull the recent changes. When you're done open a PR.

**Comment by VedantBandeJain** [comment]
hey I would like to change the background  image of the site to some thing more meaningful  please assign this issue to me.

**Comment by NisooJadhav** [comment]
> hey I would like to change the background image of the site to something more meaningful please assign this issue to me.

@VedantBandeJain it's the feature of the site to serve new backgrounds everytime the site is refreshed, do you have any other suggestions?

**Comment by VedantBandeJain** [comment]
we can add a div showing date too.

**Comment by NisooJadhav** [comment]
> we can add a div showing date too.

yes we were thinking about adding it below time, in small fonts
