### ISSUE TITLE
🐛: Timer is not staring/working

### ISSUE THREAD

**Issue by withrvr** [NisooJadhav/clock#42]
- https://nisoojadhav.github.io/clock/index.html
- I think it may have worked locally, but not working online
- ![image](https://user-images.githubusercontent.com/69628500/205730390-137e6448-98bf-4203-adbd-b9d9c419e3e4.png)

**Comment by NisooJadhav** [comment]
@withrvr thank you for your review, you need to allow notifications for this site in the URL bar when the Lock icon for the site is located. Then it will work.

![Untitled](https://user-images.githubusercontent.com/68807845/205793725-717a611c-c2a9-44cd-a056-b573d2d88947.png)
